using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TShockDBEditor
{
    public class Itemlist
    {
        public static List<string> ItemList = new List<string>();

        public static void AddItems()
        {
            ItemList.Add("Iron Pickaxe");
            ItemList.Add("Dirt Block");
            ItemList.Add("Stone Block");
            ItemList.Add("Iron Broadsword");
            ItemList.Add("Mushroom");
            ItemList.Add("Iron Shortsword");
            ItemList.Add("Iron Hammer");
            ItemList.Add("Torch");
            ItemList.Add("Wood");
            ItemList.Add("Iron Axe");
            ItemList.Add("Iron Ore");
            ItemList.Add("Copper Ore");
            ItemList.Add("Gold Ore");
            ItemList.Add("Silver Ore");
            ItemList.Add("Copper Watch");
            ItemList.Add("Silver Watch");
            ItemList.Add("Gold Watch");
            ItemList.Add("Depth Meter");
            ItemList.Add("Gold Bar");
            ItemList.Add("Copper Bar");
            ItemList.Add("Silver Bar");
            ItemList.Add("Iron Bar");
            ItemList.Add("Gel");
            ItemList.Add("Wooden Sword");
            ItemList.Add("Wooden Door");
            ItemList.Add("Stone Wall");
            ItemList.Add("Acorn");
            ItemList.Add("Lesser Healing Potion");
            ItemList.Add("Life Crystal");
            ItemList.Add("Dirt Wall");
            ItemList.Add("Bottle");
            ItemList.Add("Wooden Table");
            ItemList.Add("Furnace");
            ItemList.Add("Wooden Chair");
            ItemList.Add("Iron Anvil");
            ItemList.Add("Work Bench");
            ItemList.Add("Goggles");
            ItemList.Add("Lens");
            ItemList.Add("Wooden Bow");
            ItemList.Add("Wooden Arrow");
            ItemList.Add("Flaming Arrow");
            ItemList.Add("Shuriken");
            ItemList.Add("Suspicious Looking Eye");
            ItemList.Add("Demon Bow");
            ItemList.Add("War Axe of the Night");
            ItemList.Add("Light's Bane");
            ItemList.Add("Unholy Arrow");
            ItemList.Add("Chest");
            ItemList.Add("Band of Regeneration");
            ItemList.Add("Magic Mirror");
            ItemList.Add("Jester's Arrow");
            ItemList.Add("Angel Statue");
            ItemList.Add("Cloud in a Bottle");
            ItemList.Add("Hermes Boots");
            ItemList.Add("Enchanted Boomerang");
            ItemList.Add("Demonite Ore");
            ItemList.Add("Demonite Bar");
            ItemList.Add("Heart");
            ItemList.Add("Corrupt Seeds");
            ItemList.Add("Vile Mushroom");
            ItemList.Add("Ebonstone Block");
            ItemList.Add("Grass Seeds");
            ItemList.Add("Sunflower");
            ItemList.Add("Vilethorn");
            ItemList.Add("Starfury");
            ItemList.Add("Purification Powder");
            ItemList.Add("Vile Powder");
            ItemList.Add("Rotten Chunk");
            ItemList.Add("Worm Tooth");
            ItemList.Add("Worm Food");
            ItemList.Add("Copper Coin");
            ItemList.Add("Silver Coin");
            ItemList.Add("Gold Coin");
            ItemList.Add("Platinum Coin");
            ItemList.Add("Fallen Star");
            ItemList.Add("Copper Greaves");
            ItemList.Add("Iron Greaves");
            ItemList.Add("Silver Greaves");
            ItemList.Add("Gold Greaves");
            ItemList.Add("Copper Chainmail");
            ItemList.Add("Iron Chainmail");
            ItemList.Add("Silver Chainmail");
            ItemList.Add("Gold Chainmail");
            ItemList.Add("Grappling Hook");
            ItemList.Add("Iron Chain");
            ItemList.Add("Shadow Scale");
            ItemList.Add("Piggy Bank");
            ItemList.Add("Mining Helmet");
            ItemList.Add("Copper Helmet");
            ItemList.Add("Iron Helmet");
            ItemList.Add("Silver Helmet");
            ItemList.Add("Gold Helmet");
            ItemList.Add("Wood Wall");
            ItemList.Add("Wood Platform");
            ItemList.Add("Flintlock Pistol");
            ItemList.Add("Musket");
            ItemList.Add("Musket Ball");
            ItemList.Add("Minishark");
            ItemList.Add("Iron Bow");
            ItemList.Add("Shadow Greaves");
            ItemList.Add("Shadow Scalemail");
            ItemList.Add("Shadow Helmet");
            ItemList.Add("Nightmare Pickaxe");
            ItemList.Add("The Breaker");
            ItemList.Add("Candle");
            ItemList.Add("Copper Chandelier");
            ItemList.Add("Silver Chandelier");
            ItemList.Add("Gold Chandelier");
            ItemList.Add("Mana Crystal");
            ItemList.Add("Lesser Mana Potion");
            ItemList.Add("Band of Starpower");
            ItemList.Add("Flower of Fire");
            ItemList.Add("Magic Missile");
            ItemList.Add("Dirt Rod");
            ItemList.Add("Orb of Light");
            ItemList.Add("Meteorite");
            ItemList.Add("Meteorite Bar");
            ItemList.Add("Hook");
            ItemList.Add("Flamarang");
            ItemList.Add("Molten Fury");
            ItemList.Add("Fiery Greatsword");
            ItemList.Add("Molten Pickaxe");
            ItemList.Add("Meteor Helmet");
            ItemList.Add("Meteor Suit");
            ItemList.Add("Meteor Leggings");
            ItemList.Add("Bottled Water");
            ItemList.Add("Space Gun");
            ItemList.Add("Rocket Boots");
            ItemList.Add("Gray Brick");
            ItemList.Add("Gray Brick Wall");
            ItemList.Add("Red Brick");
            ItemList.Add("Red Brick Wall");
            ItemList.Add("Clay Block");
            ItemList.Add("Blue Brick");
            ItemList.Add("Blue Brick Wall");
            ItemList.Add("Chain Lantern");
            ItemList.Add("Green Brick");
            ItemList.Add("Green Brick Wall");
            ItemList.Add("Pink Brick");
            ItemList.Add("Pink Brick Wall");
            ItemList.Add("Gold Brick");
            ItemList.Add("Gold Brick Wall");
            ItemList.Add("Silver Brick");
            ItemList.Add("Silver Brick Wall");
            ItemList.Add("Copper Brick");
            ItemList.Add("Copper Brick Wall");
            ItemList.Add("Spike");
            ItemList.Add("Water Candle");
            ItemList.Add("Book");
            ItemList.Add("Cobweb");
            ItemList.Add("Necro Helmet");
            ItemList.Add("Necro Breastplate");
            ItemList.Add("Necro Greaves");
            ItemList.Add("Bone");
            ItemList.Add("Muramasa");
            ItemList.Add("Cobalt Shield");
            ItemList.Add("Aqua Scepter");
            ItemList.Add("Lucky Horseshoe");
            ItemList.Add("Shiny Red Balloon");
            ItemList.Add("Harpoon");
            ItemList.Add("Spiky Ball");
            ItemList.Add("Ball 'O Hurt");
            ItemList.Add("Blue Moon");
            ItemList.Add("Handgun");
            ItemList.Add("Water Bolt");
            ItemList.Add("Bomb");
            ItemList.Add("Dynamite");
            ItemList.Add("Grenade");
            ItemList.Add("Sand Block");
            ItemList.Add("Glass");
            ItemList.Add("Sign");
            ItemList.Add("Ash Block");
            ItemList.Add("Obsidian");
            ItemList.Add("Hellstone");
            ItemList.Add("Hellstone Bar");
            ItemList.Add("Mud Block");
            ItemList.Add("Sapphire");
            ItemList.Add("Ruby");
            ItemList.Add("Emerald");
            ItemList.Add("Topaz");
            ItemList.Add("Amethyst");
            ItemList.Add("Diamond");
            ItemList.Add("Glowing Mushroom");
            ItemList.Add("Star");
            ItemList.Add("Ivy Whip");
            ItemList.Add("Breathing Reed");
            ItemList.Add("Flipper");
            ItemList.Add("Healing Potion");
            ItemList.Add("Mana Potion");
            ItemList.Add("Blade of Grass");
            ItemList.Add("Thorn Chakrum");
            ItemList.Add("Obsidian Brick");
            ItemList.Add("Obsidian Skull");
            ItemList.Add("Mushroom Grass Seeds");
            ItemList.Add("Jungle Grass Seeds");
            ItemList.Add("Wooden Hammer");
            ItemList.Add("Star Cannon");
            ItemList.Add("Blue Phaseblade");
            ItemList.Add("Red Phaseblade");
            ItemList.Add("Green Phaseblade");
            ItemList.Add("Purple Phaseblade");
            ItemList.Add("White Phaseblade");
            ItemList.Add("Yellow Phaseblade");
            ItemList.Add("Meteor Hamaxe");
            ItemList.Add("Empty Bucket");
            ItemList.Add("Water Bucket");
            ItemList.Add("Lava Bucket");
            ItemList.Add("Jungle Rose");
            ItemList.Add("Stinger");
            ItemList.Add("Vine");
            ItemList.Add("Feral Claws");
            ItemList.Add("Anklet of the Wind");
            ItemList.Add("Staff of Regrowth");
            ItemList.Add("Hellstone Brick");
            ItemList.Add("Whoopie Cushion");
            ItemList.Add("Shackle");
            ItemList.Add("Molten Hamaxe");
            ItemList.Add("Flamelash");
            ItemList.Add("Phoenix Blaster");
            ItemList.Add("Sunfury");
            ItemList.Add("Hellforge");
            ItemList.Add("Clay Pot");
            ItemList.Add("Nature's Gift");
            ItemList.Add("Bed");
            ItemList.Add("Silk");
            ItemList.Add("Lesser Restoration Potion");
            ItemList.Add("Restoration Potion");
            ItemList.Add("Jungle Hat");
            ItemList.Add("Jungle Shirt");
            ItemList.Add("Jungle Pants");
            ItemList.Add("Molten Helmet");
            ItemList.Add("Molten Breastplate");
            ItemList.Add("Molten Greaves");
            ItemList.Add("Meteor Shot");
            ItemList.Add("Sticky Bomb");
            ItemList.Add("Black Lens");
            ItemList.Add("Sunglasses");
            ItemList.Add("Wizard Hat");
            ItemList.Add("Top Hat");
            ItemList.Add("Tuxedo Shirt");
            ItemList.Add("Tuxedo Pants");
            ItemList.Add("Summer Hat");
            ItemList.Add("Bunny Hood");
            ItemList.Add("Plumber's Hat");
            ItemList.Add("Plumber's Shirt");
            ItemList.Add("Plumber's Pants");
            ItemList.Add("Hero's Hat");
            ItemList.Add("Hero's Shirt");
            ItemList.Add("Hero's Pants");
            ItemList.Add("Fish Bowl");
            ItemList.Add("Archaeologist's Hat");
            ItemList.Add("Archaeologist's Jacket");
            ItemList.Add("Archaeologist's Pants");
            ItemList.Add("Black Dye");
            ItemList.Add("Green Dye");
            ItemList.Add("Ninja Hood");
            ItemList.Add("Ninja Shirt");
            ItemList.Add("Ninja Pants");
            ItemList.Add("Leather");
            ItemList.Add("Red Hat");
            ItemList.Add("Goldfish");
            ItemList.Add("Robe");
            ItemList.Add("Robot Hat");
            ItemList.Add("Gold Crown");
            ItemList.Add("Hellfire Arrow");
            ItemList.Add("Sandgun");
            ItemList.Add("Guide Voodoo Doll");
            ItemList.Add("Diving Helmet");
            ItemList.Add("Familiar Shirt");
            ItemList.Add("Familiar Pants");
            ItemList.Add("Familiar Wig");
            ItemList.Add("Demon Scythe");
            ItemList.Add("Night's Edge");
            ItemList.Add("Dark Lance");
            ItemList.Add("Coral");
            ItemList.Add("Cactus");
            ItemList.Add("Trident");
            ItemList.Add("Silver Bullet");
            ItemList.Add("Throwing Knife");
            ItemList.Add("Spear");
            ItemList.Add("Blowpipe");
            ItemList.Add("Glowstick");
            ItemList.Add("Seed");
            ItemList.Add("Wooden Boomerang");
            ItemList.Add("Aglet");
            ItemList.Add("Sticky Glowstick");
            ItemList.Add("Poisoned Knife");
            ItemList.Add("Obsidian Skin Potion");
            ItemList.Add("Regeneration Potion");
            ItemList.Add("Swiftness Potion");
            ItemList.Add("Gills potion");
            ItemList.Add("Ironskin Potion");
            ItemList.Add("Mana Regeneration Potion");
            ItemList.Add("Magic Power Potion");
            ItemList.Add("Featherfall Potion");
            ItemList.Add("Spelunker Potion");
            ItemList.Add("Invisibility Potion");
            ItemList.Add("Shine Potion");
            ItemList.Add("Night Owl Potion");
            ItemList.Add("Battle Potion");
            ItemList.Add("Thorns Potion");
            ItemList.Add("Water Walking Potion");
            ItemList.Add("Archery Potion");
            ItemList.Add("Hunter Potion");
            ItemList.Add("Gravitation Potion");
            ItemList.Add("Gold Chest");
            ItemList.Add("Daybloom Seeds");
            ItemList.Add("Moonglow Seeds");
            ItemList.Add("Blinkroot Seeds");
            ItemList.Add("Deathweed Seeds");
            ItemList.Add("Waterleaf Seeds");
            ItemList.Add("Fireblossom Seeds");
            ItemList.Add("Daybloom");
            ItemList.Add("Moonglow");
            ItemList.Add("Blinkroot");
            ItemList.Add("Deathweed");
            ItemList.Add("Waterleaf");
            ItemList.Add("Fireblossom");
            ItemList.Add("Shark Fin");
            ItemList.Add("Feather");
            ItemList.Add("Tombstone");
            ItemList.Add("Mime Mask");
            ItemList.Add("Antlion Mandible");
            ItemList.Add("Illegal Gun Parts");
            ItemList.Add("The Doctor's Shirt");
            ItemList.Add("The Doctor's Pants");
        }
    }
}
